### ISSUE TITLE
Not able to install

### ISSUE THREAD

**Issue by avrajit** [bbglab/oncodrivefml#10]
System_info
Distributor ID:	Ubuntu
Description:	Ubuntu 22.04.4 LTS
Release:	22.04
Codename:	jammy
python version: 3.12.2

I was trying to install oncodrivefml using differnt methods but not able to do it successfully. 
with conda there is dependency conflict with pandas version which I removed and tried again but not able to do. Same with pip. Finally I downloded the  latest source code from your github and did `make install-dev`

and installation not done I am stuck with these errors below. I tried to search if I can bypass these errors but didn't get proper solution. Please let me know how to install this. The installation log bellow:

(base) hp@hp:/user/tools$ cd oncodrivefml-master/
(base) hp@hp:/user/tools/oncodrivefml-master$ make install-dev
Preparing virtual environment ...
python -m venv ./.venv
./.venv/bin/pip install -U pip ruff setuptools wheel build twine
Requirement already satisfied: pip in ./.venv/lib/python3.12/site-packages (24.0)
Collecting pip
  Using cached pip-24.3.1-py3-none-any.whl.metadata (3.7 kB)
Collecting ruff
  Downloading ruff-0.7.4-py3-none-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (25 kB)
Collecting setuptools
  Using cached setuptools-75.6.0-py3-none-any.whl.metadata (6.7 kB)
Collecting wheel
  Using cached wheel-0.45.0-py3-none-any.whl.metadata (2.3 kB)
Collecting build
  Downloading build-1.2.2.post1-py3-none-any.whl.metadata (6.5 kB)
Collecting twine
  Downloading twine-5.1.1-py3-none-any.whl.metadata (3.5 kB)
Collecting packaging>=19.1 (from build)
  Using cached packaging-24.2-py3-none-any.whl.metadata (3.2 kB)
Collecting pyproject_hooks (from build)
  Downloading pyproject_hooks-1.2.0-py3-none-any.whl.metadata (1.3 kB)
Collecting pkginfo>=1.8.1 (from twine)
  Downloading pkginfo-1.11.2-py3-none-any.whl.metadata (11 kB)
Collecting readme-renderer>=35.0 (from twine)
  Downloading readme_renderer-44.0-py3-none-any.whl.metadata (2.8 kB)
Collecting requests>=2.20 (from twine)
  Downloading requests-2.32.3-py3-none-any.whl.metadata (4.6 kB)
Collecting requests-toolbelt!=0.9.0,>=0.8.0 (from twine)
  Downloading requests_toolbelt-1.0.0-py2.py3-none-any.whl.metadata (14 kB)
Collecting urllib3>=1.26.0 (from twine)
  Downloading urllib3-2.2.3-py3-none-any.whl.metadata (6.5 kB)
Collecting importlib-metadata>=3.6 (from twine)
  Downloading importlib_metadata-8.5.0-py3-none-any.whl.metadata (4.8 kB)
Collecting keyring>=15.1 (from twine)
  Downloading keyring-25.5.0-py3-none-any.whl.metadata (20 kB)
Collecting rfc3986>=1.4.0 (from twine)
  Downloading rfc3986-2.0.0-py2.py3-none-any.whl.metadata (6.6 kB)
Collecting rich>=12.0.0 (from twine)
  Downloading rich-13.9.4-py3-none-any.whl.metadata (18 kB)
Collecting pkginfo>=1.8.1 (from twine)
  Downloading pkginfo-1.10.0-py3-none-any.whl.metadata (11 kB)
Collecting zipp>=3.20 (from importlib-metadata>=3.6->twine)
  Downloading zipp-3.21.0-py3-none-any.whl.metadata (3.7 kB)
Collecting jaraco.classes (from keyring>=15.1->twine)
  Downloading jaraco.classes-3.4.0-py3-none-any.whl.metadata (2.6 kB)
Collecting jaraco.functools (from keyring>=15.1->twine)
  Downloading jaraco.functools-4.1.0-py3-none-any.whl.metadata (2.9 kB)
Collecting jaraco.context (from keyring>=15.1->twine)
  Downloading jaraco.context-6.0.1-py3-none-any.whl.metadata (4.1 kB)
Collecting SecretStorage>=3.2 (from keyring>=15.1->twine)
  Downloading SecretStorage-3.3.3-py3-none-any.whl.metadata (4.0 kB)
Collecting jeepney>=0.4.2 (from keyring>=15.1->twine)
  Downloading jeepney-0.8.0-py3-none-any.whl.metadata (1.3 kB)
Collecting nh3>=0.2.14 (from readme-renderer>=35.0->twine)
  Downloading nh3-0.2.18-cp37-abi3-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (1.7 kB)
Collecting docutils>=0.21.2 (from readme-renderer>=35.0->twine)
  Downloading docutils-0.21.2-py3-none-any.whl.metadata (2.8 kB)
Collecting Pygments>=2.5.1 (from readme-renderer>=35.0->twine)
  Downloading pygments-2.18.0-py3-none-any.whl.metadata (2.5 kB)
Collecting charset-normalizer<4,>=2 (from requests>=2.20->twine)
  Downloading charset_normalizer-3.4.0-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (34 kB)
Collecting idna<4,>=2.5 (from requests>=2.20->twine)
  Downloading idna-3.10-py3-none-any.whl.metadata (10 kB)
Collecting certifi>=2017.4.17 (from requests>=2.20->twine)
  Downloading certifi-2024.8.30-py3-none-any.whl.metadata (2.2 kB)
Collecting markdown-it-py>=2.2.0 (from rich>=12.0.0->twine)
  Downloading markdown_it_py-3.0.0-py3-none-any.whl.metadata (6.9 kB)
Collecting mdurl~=0.1 (from markdown-it-py>=2.2.0->rich>=12.0.0->twine)
  Downloading mdurl-0.1.2-py3-none-any.whl.metadata (1.6 kB)
Collecting cryptography>=2.0 (from SecretStorage>=3.2->keyring>=15.1->twine)
  Downloading cryptography-43.0.3-cp39-abi3-manylinux_2_28_x86_64.whl.metadata (5.4 kB)
Collecting more-itertools (from jaraco.classes->keyring>=15.1->twine)
  Downloading more_itertools-10.5.0-py3-none-any.whl.metadata (36 kB)
Collecting cffi>=1.12 (from cryptography>=2.0->SecretStorage>=3.2->keyring>=15.1->twine)
  Downloading cffi-1.17.1-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (1.5 kB)
Collecting pycparser (from cffi>=1.12->cryptography>=2.0->SecretStorage>=3.2->keyring>=15.1->twine)
  Downloading pycparser-2.22-py3-none-any.whl.metadata (943 bytes)
Using cached pip-24.3.1-py3-none-any.whl (1.8 MB)
Downloading ruff-0.7.4-py3-none-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (11.1 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 11.1/11.1 MB 173.6 kB/s eta 0:00:00
Using cached setuptools-75.6.0-py3-none-any.whl (1.2 MB)
Using cached wheel-0.45.0-py3-none-any.whl (72 kB)
Downloading build-1.2.2.post1-py3-none-any.whl (22 kB)
Downloading twine-5.1.1-py3-none-any.whl (38 kB)
Downloading importlib_metadata-8.5.0-py3-none-any.whl (26 kB)
Downloading keyring-25.5.0-py3-none-any.whl (39 kB)
Using cached packaging-24.2-py3-none-any.whl (65 kB)
Downloading pkginfo-1.10.0-py3-none-any.whl (30 kB)
Downloading readme_renderer-44.0-py3-none-any.whl (13 kB)
Downloading requests-2.32.3-py3-none-any.whl (64 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 64.9/64.9 kB 381.3 kB/s eta 0:00:00
Downloading requests_toolbelt-1.0.0-py2.py3-none-any.whl (54 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 54.5/54.5 kB 482.2 kB/s eta 0:00:00
Downloading rfc3986-2.0.0-py2.py3-none-any.whl (31 kB)
Downloading rich-13.9.4-py3-none-any.whl (242 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 242.4/242.4 kB 234.7 kB/s eta 0:00:00
Downloading urllib3-2.2.3-py3-none-any.whl (126 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 126.3/126.3 kB 101.1 kB/s eta 0:00:00
Downloading pyproject_hooks-1.2.0-py3-none-any.whl (10 kB)
Downloading certifi-2024.8.30-py3-none-any.whl (167 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 167.3/167.3 kB 296.8 kB/s eta 0:00:00
Downloading charset_normalizer-3.4.0-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (143 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 143.8/143.8 kB 132.3 kB/s eta 0:00:00
Downloading docutils-0.21.2-py3-none-any.whl (587 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 587.4/587.4 kB 125.9 kB/s eta 0:00:00
Downloading idna-3.10-py3-none-any.whl (70 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 70.4/70.4 kB 93.9 kB/s eta 0:00:00
Downloading jeepney-0.8.0-py3-none-any.whl (48 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 48.4/48.4 kB 277.2 kB/s eta 0:00:00
Downloading markdown_it_py-3.0.0-py3-none-any.whl (87 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 87.5/87.5 kB 331.0 kB/s eta 0:00:00
Downloading nh3-0.2.18-cp37-abi3-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (769 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 769.2/769.2 kB 147.4 kB/s eta 0:00:00
Downloading pygments-2.18.0-py3-none-any.whl (1.2 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.2/1.2 MB 158.7 kB/s eta 0:00:00
Downloading SecretStorage-3.3.3-py3-none-any.whl (15 kB)
Downloading zipp-3.21.0-py3-none-any.whl (9.6 kB)
Downloading jaraco.classes-3.4.0-py3-none-any.whl (6.8 kB)
Downloading jaraco.context-6.0.1-py3-none-any.whl (6.8 kB)
Downloading jaraco.functools-4.1.0-py3-none-any.whl (10 kB)
Downloading cryptography-43.0.3-cp39-abi3-manylinux_2_28_x86_64.whl (4.0 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 4.0/4.0 MB 147.7 kB/s eta 0:00:00
Downloading mdurl-0.1.2-py3-none-any.whl (10.0 kB)
Downloading more_itertools-10.5.0-py3-none-any.whl (60 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 61.0/61.0 kB 191.7 kB/s eta 0:00:00
Downloading cffi-1.17.1-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (479 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 479.4/479.4 kB 266.8 kB/s eta 0:00:00
Downloading pycparser-2.22-py3-none-any.whl (117 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 117.6/117.6 kB 258.6 kB/s eta 0:00:00
Installing collected packages: nh3, zipp, wheel, urllib3, setuptools, ruff, rfc3986, pyproject_hooks, Pygments, pycparser, pkginfo, pip, packaging, more-itertools, mdurl, jeepney, jaraco.context, idna, docutils, charset-normalizer, certifi, requests, readme-renderer, markdown-it-py, jaraco.functools, jaraco.classes, importlib-metadata, cffi, build, rich, requests-toolbelt, cryptography, SecretStorage, keyring, twine
  Attempting uninstall: pip
    Found existing installation: pip 24.0
    Uninstalling pip-24.0:
      Successfully uninstalled pip-24.0
Successfully installed Pygments-2.18.0 SecretStorage-3.3.3 build-1.2.2.post1 certifi-2024.8.30 cffi-1.17.1 charset-normalizer-3.4.0 cryptography-43.0.3 docutils-0.21.2 idna-3.10 importlib-metadata-8.5.0 jaraco.classes-3.4.0 jaraco.context-6.0.1 jaraco.functools-4.1.0 jeepney-0.8.0 keyring-25.5.0 markdown-it-py-3.0.0 mdurl-0.1.2 more-itertools-10.5.0 nh3-0.2.18 packaging-24.2 pip-24.3.1 pkginfo-1.10.0 pycparser-2.22 pyproject_hooks-1.2.0 readme-renderer-44.0 requests-2.32.3 requests-toolbelt-1.0.0 rfc3986-2.0.0 rich-13.9.4 ruff-0.7.4 setuptools-75.6.0 twine-5.1.1 urllib3-2.2.3 wheel-0.45.0 zipp-3.21.0
==> Success!
./.venv/bin/pip install -e .
Obtaining file:///user/tools/oncodrivefml-master
  Preparing metadata (setup.py) ... done
Collecting ago==0.0.93 (from oncodrivefml==2.5.0)
  Using cached ago-0.0.93.tar.gz (3.3 kB)
  Preparing metadata (setup.py) ... done
Collecting bgcache==0.1 (from oncodrivefml==2.5.0)
  Using cached bgcache-0.1.tar.gz (3.0 kB)
  Preparing metadata (setup.py) ... done
Collecting bgconfig==0.10 (from oncodrivefml==2.5.0)
  Using cached bgconfig-0.10.tar.gz (3.6 kB)
  Preparing metadata (setup.py) ... done
Collecting bgdata==2.0.4 (from oncodrivefml==2.5.0)
  Using cached bgdata-2.0.4-py3-none-any.whl.metadata (528 bytes)
Collecting bglogs==0.6 (from oncodrivefml==2.5.0)
  Using cached bglogs-0.6.tar.gz (4.9 kB)
  Preparing metadata (setup.py) ... done
Collecting bgparsers==0.10 (from oncodrivefml==2.5.0)
  Using cached bgparsers-0.10-py2.py3-none-any.whl.metadata (426 bytes)
Collecting bgreference==0.6 (from oncodrivefml==2.5.0)
  Using cached bgreference-0.6.tar.gz (3.0 kB)
  Preparing metadata (setup.py) ... done
Collecting bgsignature==0.2 (from oncodrivefml==2.5.0)
  Using cached bgsignature-0.2.tar.gz (11 kB)
  Preparing metadata (setup.py) ... done
Collecting bokeh==1.4.0 (from oncodrivefml==2.5.0)
  Using cached bokeh-1.4.0.tar.gz (32.4 MB)
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error
  
  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [21 lines of output]
      /tmp/pip-install-8x_lwrmk/bokeh_9cc2ad28f969464c8a2901b7766bbf3d/versioneer.py:417: SyntaxWarning: invalid escape sequence '\s'
        LONG_VERSION_PY['git'] = '''
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/tmp/pip-install-8x_lwrmk/bokeh_9cc2ad28f969464c8a2901b7766bbf3d/setup.py", line 124, in <module>
          version=get_version(),
                  ^^^^^^^^^^^^^
        File "/tmp/pip-install-8x_lwrmk/bokeh_9cc2ad28f969464c8a2901b7766bbf3d/_setup_support.py", line 240, in get_version
          return versioneer.get_version()
                 ^^^^^^^^^^^^^^^^^^^^^^^^
        File "/tmp/pip-install-8x_lwrmk/bokeh_9cc2ad28f969464c8a2901b7766bbf3d/versioneer.py", line 1487, in get_version
          return get_versions()["version"]
                 ^^^^^^^^^^^^^^
        File "/tmp/pip-install-8x_lwrmk/bokeh_9cc2ad28f969464c8a2901b7766bbf3d/versioneer.py", line 1419, in get_versions
          cfg = get_config_from_root(root)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/tmp/pip-install-8x_lwrmk/bokeh_9cc2ad28f969464c8a2901b7766bbf3d/versioneer.py", line 341, in get_config_from_root
          parser = configparser.SafeConfigParser()
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      AttributeError: module 'configparser' has no attribute 'SafeConfigParser'. Did you mean: 'RawConfigParser'?
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.
make: *** [Makefile:108: install-dev] Error 1

**Comment by chris-zen** [comment]
Hi @avrajit , unfortunately OncodeiveFML requires Python 3.11 or less. But you are using 3.12. Could you please try again using Python 3.11?
