### ISSUE TITLE
Error Encountered Running OncodriveFML Example Dataset

### ISSUE THREAD

**Issue by FunGeST** [bbglab/oncodrivefml#6]
I recently installed OncodriveFML, using conda (conda install -c bbglab oncodrivefml ) but I encountered an error while running the example datasets at this step:
2024-10-30 20:53:24 oncodrivefml INFO -- Building regions tree
Here’s the error message:
Do you have any insights on what might be causing this?
Sandrine

Error message
Traceback (most recent call last):
  File "/mnt/MD1200_5/Workdir_Sandrine/MyTOOLS/miniconda3/envs/oncodrivefml_env/bin/oncodrivefml", line 11, in <module>
    sys.exit(cmdline())
  File "/mnt/MD1200_5/Workdir_Sandrine/MyTOOLS/miniconda3/envs/oncodrivefml_env/lib/python3.6/site-packages/click/core.py", line 1137, in __call__
    return self.main(*args, **kwargs)
  File "/mnt/MD1200_5/Workdir_Sandrine/MyTOOLS/miniconda3/envs/oncodrivefml_env/lib/python3.6/site-packages/click/core.py", line 1062, in main
    rv = self.invoke(ctx)
  File "/mnt/MD1200_5/Workdir_Sandrine/MyTOOLS/miniconda3/envs/oncodrivefml_env/lib/python3.6/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/mnt/MD1200_5/Workdir_Sandrine/MyTOOLS/miniconda3/envs/oncodrivefml_env/lib/python3.6/site-packages/click/core.py", line 763, in invoke
    return __callback(*args, **kwargs)
  File "/mnt/MD1200_5/Workdir_Sandrine/MyTOOLS/miniconda3/envs/oncodrivefml_env/lib/python3.6/site-packages/oncodrivefml/main.py", line 104, in cmdline
    override_config)
  File "/mnt/MD1200_5/Workdir_Sandrine/MyTOOLS/miniconda3/envs/oncodrivefml_env/lib/python3.6/site-packages/oncodrivefml/main.py", line 56, in main
    analysis.run()
  File "/mnt/MD1200_5/Workdir_Sandrine/MyTOOLS/miniconda3/envs/oncodrivefml_env/lib/python3.6/site-packages/oncodrivefml/oncodrivefml.py", line 189, in run
    save_pickle=self.generate_pickle)
  File "/mnt/MD1200_5/Workdir_Sandrine/MyTOOLS/miniconda3/envs/oncodrivefml_env/lib/python3.6/site-packages/oncodrivefml/load.py", line 230, in load_and_map_variants
    elements_tree = load_elements_tree(elements_file)
  File "/mnt/MD1200_5/Workdir_Sandrine/MyTOOLS/miniconda3/envs/oncodrivefml_env/lib/python3.6/site-packages/bgcache/decorator.py", line 81, in new_function
    cached_value = old_function(input_file)
  File "/mnt/MD1200_5/Workdir_Sandrine/MyTOOLS/miniconda3/envs/oncodrivefml_env/lib/python3.6/site-packages/oncodrivefml/load.py", line 181, in load_elements_tree
    return build_regions_tree(elements)
  File "/mnt/MD1200_5/Workdir_Sandrine/MyTOOLS/miniconda3/envs/oncodrivefml_env/lib/python3.6/site-packages/oncodrivefml/load.py", line 164, in build_regions_tree
    for i, (k, allr) in enumerate(regions.items()):
AttributeError: 'generator' object has no attribute 'items'

**Comment by FedericaBrando** [comment]
Hi, thanks for reporting,

could you install the `pip` package instead of the conda. OncodriveFML should be 2.4.0, while the conda package is 2.2.0.

See if this solves the problem. 
Thanks
