### ISSUE TITLE
bgdata.errors.TagNotFound: Tag master for package genomicscores/caddpack/1.0 not found

### ISSUE THREAD

**Issue by Conghui2023** [bbglab/oncodrivefml#7]
Hi, when I run the 'run.sh' on the 'example' you provided, I encountered this problem, do you know the reason, and how can I solve it?

Traceback (most recent call last):
  File "/share/home/luoylLab/liconghui/.conda/envs/oncodrivefml_env/bin/oncodrivefml", line 11, in <module>
    sys.exit(cmdline())
  File "/share/home/luoylLab/liconghui/.conda/envs/oncodrivefml_env/lib/python3.7/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/share/home/luoylLab/liconghui/.conda/envs/oncodrivefml_env/lib/python3.7/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/share/home/luoylLab/liconghui/.conda/envs/oncodrivefml_env/lib/python3.7/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/share/home/luoylLab/liconghui/.conda/envs/oncodrivefml_env/lib/python3.7/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/share/home/luoylLab/liconghui/.conda/envs/oncodrivefml_env/lib/python3.7/site-packages/oncodrivefml/main.py", line 104, in cmdline
    override_config)
  File "/share/home/luoylLab/liconghui/.conda/envs/oncodrivefml_env/lib/python3.7/site-packages/oncodrivefml/main.py", line 39, in main
    configuration = load_configuration(config_file, override=config_override_dict)
  File "/share/home/luoylLab/liconghui/.conda/envs/oncodrivefml_env/lib/python3.7/site-packages/oncodrivefml/config.py", line 33, in load_configuration
    return BGConfig(config_template, config_file=config_file, use_env_vars=True, override_values=override, unrepr=False)
  File "/share/home/luoylLab/liconghui/.conda/envs/oncodrivefml_env/lib/python3.7/site-packages/bgconfig.py", line 232, in __init__
    res = self.validate(Validator(), preserve_errors=True)
  File "/share/home/luoylLab/liconghui/.conda/envs/oncodrivefml_env/lib/python3.7/site-packages/configobj/__init__.py", line 2301, in validate
    check = self.validate(validator, preserve_errors=preserve_errors, copy=copy, section=section[entry])
  File "/share/home/luoylLab/liconghui/.conda/envs/oncodrivefml_env/lib/python3.7/site-packages/configobj/__init__.py", line 2254, in validate
    val = section[entry]
  File "/share/home/luoylLab/liconghui/.conda/envs/oncodrivefml_env/lib/python3.7/site-packages/configobj/__init__.py", line 552, in __getitem__
    return self._interpolate(key, val)
  File "/share/home/luoylLab/liconghui/.conda/envs/oncodrivefml_env/lib/python3.7/site-packages/configobj/__init__.py", line 544, in _interpolate
    return engine.interpolate(key, value)
  File "/share/home/luoylLab/liconghui/.conda/envs/oncodrivefml_env/lib/python3.7/site-packages/bgconfig.py", line 60, in interpolate
    value = self.bgdata_engine.interpolate(key, value)
  File "/share/home/luoylLab/liconghui/.conda/envs/oncodrivefml_env/lib/python3.7/site-packages/bgdata/configobj.py", line 46, in interpolate
    path = bgdata.get(match.group(1))
  File "/share/home/luoylLab/liconghui/.conda/envs/oncodrivefml_env/lib/python3.7/site-packages/bgdata/manager.py", line 220, in get
    return self._get(project, dataset, version, ref)
  File "/share/home/luoylLab/liconghui/.conda/envs/oncodrivefml_env/lib/python3.7/site-packages/bgdata/manager.py", line 201, in _get
    build = self._ref2build(pkg, ref)
  File "/share/home/luoylLab/liconghui/.conda/envs/oncodrivefml_env/lib/python3.7/site-packages/bgdata/manager.py", line 157, in _ref2build
    build = self._tag2build(pkg, ref)
  File "/share/home/luoylLab/liconghui/.conda/envs/oncodrivefml_env/lib/python3.7/site-packages/bgdata/manager.py", line 143, in _tag2build
    raise TagNotFound(err_msg)
bgdata.errors.TagNotFound: Tag master for package genomicscores/caddpack/1.0 not found (HTTPSConnectionPool(host='bbglab.irbbarcelona.org', port=443): Max retries exceeded with url: /bgdata/genomicscores/caddpack/1.0.master?e427999cf3e8c5371a16ed911bdd02 (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x2b8f28256f10>: Failed to resolve 'bbglab.irbbarcelona.org' ([Errno -2] Name or service not known)")))

**Comment by Conghui2023** [comment]
Hi, I just tried it again, but the error persists.


2024年11月13日 00:08，Federica Brando ***@***.***> 写道：


Du får ikke ofte mails fra ***@***.*** Få mere at vide om, hvorfor dette er vigtigt<https://aka.ms/LearnAboutSenderIdentification>



Hi, Thanks for reporting the error.

Could you try another time, sometimes the connection with the bbglab.irbbarcelona.org is lost and then recovered.

Please let me know if the error persists.

**Comment by FedericaBrando** [comment]
I see, can you provide me the version of oncodrivefml you are trying to run? Thanks

**Comment by Conghui2023** [comment]
Many thanks for your continued support, the version is 2.1.3

发自我的 iPhone

在 2024年11月13日，19:52，Federica Brando ***@***.***> 写道：

﻿

Du får ikke ofte mails fra ***@***.*** Få mere at vide om, hvorfor dette er vigtigt<https://aka.ms/LearnAboutSenderIdentification>


I see, can you provide me the version of oncodrivefml you are trying to run? Thanks

**Comment by Conghui2023** [comment]
I tried it again with 2.4.0 version as you suggested, but unfortunately, the issue still existed.

发自我的 iPhone

在 2024年11月13日，22:41，Federica Brando ***@***.***> 写道：

﻿

Du får ikke ofte mails fra ***@***.*** Få mere at vide om, hvorfor dette er vigtigt<https://aka.ms/LearnAboutSenderIdentification>


could you try again with the latest oncodrivefml version (2.4.0) downloaded from pip?

**Comment by FedericaBrando** [comment]
Can you confirm that you can access the following website:
[bbglab.irbbarcelona.org](https://bbglab.irbbarcelona.org)

**Comment by Conghui2023** [comment]
Yes, I can access this website.

2024年11月14日 00:11，Federica Brando ***@***.***> 写道：



Can you confirm that you can access the following website:
bbglab.irbbarcelona.org<https://bbglab.irbbarcelona.org/>

**Comment by Conghui2023** [comment]
Hi, in this case, could you please directly provide us with the download links for reference and other required documents? Thank you very much in advance

All the best,
Conghui

发自我的 iPhone

在 2024年11月14日，09:29，Conghui Li ***@***.***> 写道：

﻿ Yes, I can access this website.

2024年11月14日 00:11，Federica Brando ***@***.***> 写道：



Can you confirm that you can access the following website:
bbglab.irbbarcelona.org<https://bbglab.irbbarcelona.org/>

**Comment by FedericaBrando** [comment]
Hi,

You can try the following approach:

Before running **`OncodriveFML`**, you can download the data first with these commands [[source](https://oncodrivefml.readthedocs.io/en/latest/includes.html#run-the-example)]:
1. Remove the `~/.bgdata` folder 
2. Downloading the cadd scores:
    ```sh
    bgdata get genomicscores/caddpack/1.0
    ```
3. Downloading the genome reference:
    ```sh
    bgdata get datasets/genomereference/hg19
    ```
4. export `BGDATA_LOCAL=~/.bgdata` and `BGDATA_OFFLINE=TRUE` environment variables
5. modify the` ./run.sh` file to run with the `--debug` flag (so we are able to see what is going on in the run)
6. run the example.

Please can you also ping [bbglab.irbbarcelona.org](https://bbglab.irbbarcelona.org/) to check that is indeed reachable from your terminal? Thanks

**Comment by Conghui2023** [comment]
Hi,

The method you provided works, thanks a million! 

BTW, when I run ‘ping bbglab.irbbarcelona.org’ ,it is indeed reachable. I think it may be because my Linux environment network is not stable, so I can not download reference directly through run.sh.
